In [1]:
'''
Exercise
Predict canada's per capita income in year 2020. There is an exercise folder here on github at same level as this notebook, download that and you will find canada_per_capita_income.csv file. Using this build a regression model and predict the per capita income fo canadian citizens in year 2020

Answer
41288.69409442
'''

"\nExercise\nPredict canada's per capita income in year 2020. There is an exercise folder here on github at same level as this notebook, download that and you will find canada_per_capita_income.csv file. Using this build a regression model and predict the per capita income fo canadian citizens in year 2020\n\nAnswer\n41288.69409442\n"

In [19]:
import pandas as pd

In [33]:
data = pd.read_csv(r'canada_per_capita_income.csv')
data
data.isnull().sum()

year                       0
per capita income (US$)    0
dtype: int64

In [32]:
X = data['year'].values.reshape(-1, 1)
Y = data['per capita income (US$)'].values.reshape(-1, 1)
X

array([[1970],
       [1971],
       [1972],
       [1973],
       [1974],
       [1975],
       [1976],
       [1977],
       [1978],
       [1979],
       [1980],
       [1981],
       [1982],
       [1983],
       [1984],
       [1985],
       [1986],
       [1987],
       [1988],
       [1989],
       [1990],
       [1991],
       [1992],
       [1993],
       [1994],
       [1995],
       [1996],
       [1997],
       [1998],
       [1999],
       [2000],
       [2001],
       [2002],
       [2003],
       [2004],
       [2005],
       [2006],
       [2007],
       [2008],
       [2009],
       [2010],
       [2011],
       [2012],
       [2013],
       [2014],
       [2015],
       [2016]], dtype=int64)

In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2, random_state = 30)

In [23]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor

LinearRegression()

In [24]:
regressor.fit(X_train, Y_train)

LinearRegression()

In [25]:
Y_pred = regressor.predict(X_test)

In [27]:
Y_pred

array([[32778.94365167],
       [26280.95503871],
       [17346.22069589],
       [34403.44080491],
       [15721.72354265],
       [ 8411.48635307],
       [19782.96642575],
       [25468.70646209],
       [16533.97211927],
       [31966.69507505]])

In [28]:
# for random_state = 42 => array([[41027.67748165]])
regressor.predict([[2020]])

array([[40901.42941787]])

In [29]:
data_preds = pd.DataFrame({'Actual': Y_test.squeeze(), 'Predicted': Y_pred.squeeze()})

In [30]:
data_preds

Actual     Predicted
0  38420.52289  32778.943652
1  19232.17556  26280.955039
2  17266.09769  17346.220696
3  42665.25597  34403.440805
4  16426.72548  15721.723543
5   8355.96812   8411.486353
6  15755.82027  19782.966426
7  18601.39724  25468.706462
8  16838.67320  16533.972119
9  32755.17682  31966.695075

In [ ]:
data